library(dplyr)
main_data<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?",colClasses = c("character","character",rep("numeric",7)))
des_data<-subset(main_data,main_data$Date=="1/2/2007"|main_data=="2/2/2007")
datetime <- strptime(paste(des_data$Date, des_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot2.png",width = 480,height = 480)
plot(datetime,des_data$Global_active_power,xlab="",ylab = "Global Active Power (kilowatts)",col="black",type="l",mar=c(2,2,1,1))
dev.off()